---
- include_tasks: configure.yml
- name: Ensure mysql is running
  service:
    name: mariadb
    state: started
    enabled: true

- name: Listen on MySQL port (firewalld)
  firewalld:
    service: mysql
    state: enabled
    permanent: true
  when: ansible_distribution_file_variety == 'RedHat' and ansible_distribution_major_version == '7'

- include_tasks: secure-installation.yml
- include_tasks: databases.yml
- include_tasks: users.yml
- include_tasks: replication.yml
 
